import { IconProps } from '.';
export declare const IconRefresh: React.FC<IconProps>;
export declare const IconFemale: React.FC<IconProps>;
export declare const IconMale: React.FC<IconProps>;
export declare const IconPreviewOpen: React.FC<IconProps>;
export declare const IconPreviewClose: React.FC<IconProps>;
export declare const IconAvatar: React.FC<IconProps>;
export declare const IconTag: React.FC<IconProps>;
export declare const IconSetting: React.FC<IconProps>;
export declare const IconConfigSetting: React.FC<IconProps>;
export declare const IconCollection: React.FC<IconProps>;
export declare const IconShare: React.FC<IconProps>;
export declare const IconTranslate: React.FC<IconProps>;
export declare const IconLight: React.FC<IconProps>;
export declare const IconDark: React.FC<IconProps>;
export declare const IconSearch: React.FC<IconProps>;
